In [1]:
#Import the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
#Importing dataset
dataset = pd.read_csv('50_Startups.csv')

In [4]:
#Seperate data with features and label
features = dataset.iloc[:,[0,1,2,3]].values
label = dataset.iloc[:,[4]].values

In [5]:
#becoz i gave double square brackets thats y it decripted as a2D
features.shape

(50, 4)

In [6]:
label.shape

(50, 1)

In [15]:
#Deal with Categorical Data
#here state fied is catagorical(3loc)
#LE takes accounatable to convert each unique values into numbers
#fit_transform() applies logic(eq) on rhs and stores in lhs 
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
features[:,3]=encoder.fit_transform(features[:,3])

#One Hot Encoding --- Creation of Dummy Variable
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[3])
features = onehotencoder.fit_transform(features).toarray()
# i need numpyarray to my model otherwise it will throw error(by writing .toarray())

In [16]:
encoder.classes_

array([0, 1, 2], dtype=object)

In [17]:
features[1:10,:]

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.2333488e+05,
        1.0867917e+05, 3.0498162e+05]])

In [18]:
#Create train test set

from sklearn.cross_validation import train_test_split

X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.3,
                                                random_state=10)

In [20]:
#Create the model
from sklearn.linear_model import LinearRegression
model =LinearRegression()
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
#Test the model
y_predictions = model.predict(X_test)

In [22]:
y_predictions

array([[ 88747.29562586],
       [108285.64828057],
       [ 67559.62122416],
       [ 71615.54776722],
       [ 49467.88493178],
       [116587.75381427],
       [170839.49557058],
       [ 98588.69604141],
       [157921.40321395],
       [157978.70666821],
       [ 83938.28393205],
       [178059.49024318],
       [ 76278.75354893],
       [100205.00057172],
       [133275.0841474 ]])

In [23]:
model.score(X_test,y_test)
#1. Get the y_pred
#2. Get R2 score using y_pred and y_test

0.9796796125079976

In [24]:
#the bove one and this is same ,prefer above one only
from sklearn.metrics import r2_score
r2_score(y_test,y_predictions)

0.9796796125079977